# docker run --name api-desafio-pg -e POSTGRESQL_USERNAME=docker  -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apidesafio -p 5432:5432 bitnami/postgresql

# docker start api-desafio-pg

# docker compose up -d
# docker compose stop

version: '3'

services:
  api-desafio-pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apidesafio
